<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYankmpG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYankmpG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYankmpG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYankmpG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYankmpG\App_KernelDevDebugContainer([
    'container.build_hash' => 'YankmpG',
    'container.build_id' => 'd6985967',
    'container.build_time' => 1621258543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYankmpG');
