<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRVOWdaQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRVOWdaQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRVOWdaQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRVOWdaQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRVOWdaQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'RVOWdaQ',
    'container.build_id' => '8688aba5',
    'container.build_time' => 1622572936,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRVOWdaQ');
