<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmsCTAq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmsCTAq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmsCTAq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmsCTAq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUmsCTAq\App_KernelDevDebugContainer([
    'container.build_hash' => 'UmsCTAq',
    'container.build_id' => 'aa137852',
    'container.build_time' => 1620929929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmsCTAq');
