<?php

namespace Container5cYFZWa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ds1bIxqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ds1bIxq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ds1bIxq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'request' => ['privates', '.errored.mPxNZzk', NULL, 'Cannot determine controller argument for "App\\Controller\\TatuadorController::index()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'passwordEncoder' => '?',
            'request' => '?',
        ]);
    }
}
